language: python
python:
- '2.7'
install:
    - pip install -r requirements.txt
deploy:
  provider: pypi
  user: nuagenetworks
  password:
    secure: j0w66oEXcOEfWA2K2K/jUqbA1+qM5AhVKYALuKN6EG3Pf3rNV4r7MOJiehfDolYcIaBdN3B3IDPLUVvnv6Ef79/ws9YTErRiH8WcijMcUbb5zW/S5G/sapPgJ08qUEUNftBGUD2eLyfENPR7jZQWN35u8V1dBsPV1hb2ocUwIVBbhUjlPl31QOKAgMAw1IHfgKTSgrYLKoujtlh7TlW2EDTH/3jNNm6gH101Jtj2BX2Dfzv9vLz/TvGh9jOrBf/hX0fdgm2fXw1KdjgaizWeBiCTzNrlbTUtzOaZNXVRS1WIeqp4EEzrOYxbbsyoWJpkgUbIxvcSsWA0S0vQxgyFRSz/CfMBKy/EiM/MrcEqTdmT/WM111FkbJqDC5MYUGO+vIUEdJGGgSL5wXoXLN5Gt8zYnsobM4pFX5nz6FmHMPRhZwFbctT2Yv+xZBV7MMCqMyXCtBy5IjlTji/KPh1mdye8TaGZ7pzSlhrdKqfkC0zs1mmhrcrRBv3mJ7MdYI/BmevwuGr47b4A/9ZRWe5hVWpweBTzApGpXrcbvNdbwvXBzzNK0oHh287dIKEW6b0FnBna7+YvKgIySMmxNFJSnbpXzarpbYtxyWI4HuprmchFFWqS019NiZG6Xz2IbM8Hv9kTTZK0WD7VkhlCbt5Slwkp43BPqwekYPwry8icTsw=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: nuagenetworks/vspk-generator
    all_branches: true
